apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: songnpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: songnpipelinesjavascriptdocker 
    spec:
      containers:
        - name: songnpipelinesjavascriptdocker 
          image: hsndevopsacr.azurecr.io/songnpipelinesjavascriptdocker
          ports:
          - containerPort: 8080